'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace wsMailsSendGrid
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsMailsSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class wsMails
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarCorreoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.cmpNegocio.My.MySettings.Default.cmpNegocio_wsMailsSendGrid_wsMails
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarCorreoCompleted As EnviarCorreoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreo(ByVal credenciales As Autenticacion, ByVal informacion As Correo) As Respuesta
            Dim results() As Object = Me.Invoke("EnviarCorreo", New Object() {credenciales, informacion})
            Return CType(results(0),Respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoAsync(ByVal credenciales As Autenticacion, ByVal informacion As Correo)
            Me.EnviarCorreoAsync(credenciales, informacion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoAsync(ByVal credenciales As Autenticacion, ByVal informacion As Correo, ByVal userState As Object)
            If (Me.EnviarCorreoOperationCompleted Is Nothing) Then
                Me.EnviarCorreoOperationCompleted = AddressOf Me.OnEnviarCorreoOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreo", New Object() {credenciales, informacion}, Me.EnviarCorreoOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoCompleted(Me, New EnviarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Autenticacion
        
        Private inWebIdField As TipoWeb
        
        Private stUsuarioField As String
        
        Private stClaveField As String
        
        '''<remarks/>
        Public Property InWebId() As TipoWeb
            Get
                Return Me.inWebIdField
            End Get
            Set
                Me.inWebIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StUsuario() As String
            Get
                Return Me.stUsuarioField
            End Get
            Set
                Me.stUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StClave() As String
            Get
                Return Me.stClaveField
            End Get
            Set
                Me.stClaveField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoWeb
        
        '''<remarks/>
        Mozart
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Respuesta
        
        Private tipoField As TipoRespuesta
        
        Private valorField As String
        
        Private otroValorField As String
        
        '''<remarks/>
        Public Property Tipo() As TipoRespuesta
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OtroValor() As String
            Get
                Return Me.otroValorField
            End Get
            Set
                Me.otroValorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoRespuesta
        
        '''<remarks/>
        Exito
        
        '''<remarks/>
        Alerta
        
        '''<remarks/>
        [Error]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Adjunto
        
        Private archivoBytesField As String
        
        Private nombreArchivoField As String
        
        '''<remarks/>
        Public Property ArchivoBytes() As String
            Get
                Return Me.archivoBytesField
            End Get
            Set
                Me.archivoBytesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreArchivo() As String
            Get
                Return Me.nombreArchivoField
            End Get
            Set
                Me.nombreArchivoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Correo
        
        Private nombreEmisorField As String
        
        Private correoEmisorField As String
        
        Private destinatariosField As String
        
        Private asuntoField As String
        
        Private cuerpoTextoField As String
        
        Private cuerpoHtmlField As String
        
        Private adjuntosField() As Adjunto
        
        '''<remarks/>
        Public Property NombreEmisor() As String
            Get
                Return Me.nombreEmisorField
            End Get
            Set
                Me.nombreEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CorreoEmisor() As String
            Get
                Return Me.correoEmisorField
            End Get
            Set
                Me.correoEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Destinatarios() As String
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Asunto() As String
            Get
                Return Me.asuntoField
            End Get
            Set
                Me.asuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuerpoTexto() As String
            Get
                Return Me.cuerpoTextoField
            End Get
            Set
                Me.cuerpoTextoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuerpoHtml() As String
            Get
                Return Me.cuerpoHtmlField
            End Get
            Set
                Me.cuerpoHtmlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Adjuntos() As Adjunto()
            Get
                Return Me.adjuntosField
            End Get
            Set
                Me.adjuntosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub EnviarCorreoCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Respuesta)
            End Get
        End Property
    End Class
End Namespace
